version: '3'
services:
  rabbitmq:
    image: "rabbitmq:4.0.4-management"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    volumes:
      - C:/Containers/rabbitmq/data/:/var/lib/rabbitmq/
      - C:/Containers/rabbitmq/log/:/var/log/rabbitmq/